name: asParser
on:
  pull_request:
    branches: test
  push:
    branches: test

jobs:
  asParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: run mocha-test
        run: npm run eslint-prettier && npm run test
