name: asParser
on:
  push:
    branches: main

jobs:
  asParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: run mocha-test 
        run: npm run test