name: asParser
on:
  pull_request:
    branches: main
  push:
    branches: feature/textreplace

jobs:
  asParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: run lint
        run: npm run lint
      - name: esbuild
        run: npm run build
      - name: run mocha-test
        run: npm run test
        
